### ISSUE TITLE
ｱ！

### ISSUE THREAD

**Issue by otofune** [misskey-delta/misskey-file#6]
```
RangeError: Array buffer allocation failed
    at new ArrayBuffer (<anonymous>)
    at createUnsafeArrayBuffer (buffer.js:43:12)
    at createUnsafeBuffer (buffer.js:37:25)
    at Function.Buffer.allocUnsafeSlow (buffer.js:162:10)
    at FSReqWrap.readFileAfterStat [as oncomplete] (fs.js:368:27)
```

**Comment by otofune** [comment]
メモリ足りなかったのでは？
